"""Aggregate the Issue #58 (P1.13+) lightweight-vs-integrated architecture
comparison into one report.

Composes evidence from two sources per the frozen manifest
(docs/data/lightweight_vs_integrated_tracking/p058_lightweight_vs_integrated_tracking_v1.yaml):

- ``reuse_p031``: bytetrack_raw / bytetrack_tim read directly from the
  already-closed Issue #31 per-cell report.json files (raw_target /
  tim_target_memory duration_metrics respectively). No new replay.
- ``run_fresh``: sort_raw / sort_tim / deepsort_raw / deepsort_tim read from
  report.json files generated by this issue's own replay+evaluate runs.

Cells whose annotation is pending (per annotation_availability in the
manifest) are recorded with status "pending_annotation" and no metrics --
never fabricated, never silently omitted from accounting.

Does not rerun TIM-MARS, does not re-evaluate any bag, does not alter any
per-cell report.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = (
    REPO_ROOT
    / "docs"
    / "data"
    / "lightweight_vs_integrated_tracking"
    / "p058_lightweight_vs_integrated_tracking_v1.yaml"
)
P031_REPORT_DIR = (
    REPO_ROOT / "reports" / "p031_parameter_sensitivity_5b340c2b_2026-08-08" / "sequences"
)
P058_REPORT_DIR = REPO_ROOT / "reports" / "p058_lightweight_vs_integrated_6231fdc1_2026_08_08"
OUT_DIR = P058_REPORT_DIR / "aggregate"

DURATION_FIELDS = [
    "correct_target_duration_s",
    "wrong_target_duration_s",
    "lost_target_duration_s",
    "target_absent_but_output_valid_duration_s",
    "no_target_selected_duration_s",
]


def load_manifest() -> dict[str, Any]:
    return yaml.safe_load(MANIFEST_PATH.read_text())


def duration_row(stream_metrics: dict[str, Any]) -> dict[str, float]:
    return {field: float(stream_metrics[field]) for field in DURATION_FIELDS}


def load_p031_cell(sequence_id: str) -> dict[str, Any]:
    path = P031_REPORT_DIR / sequence_id / "baseline" / "report.json"
    return json.loads(path.read_text())


def load_p058_cell(sequence_id: str, config_id: str) -> dict[str, Any] | None:
    path = P058_REPORT_DIR / "sequences" / sequence_id / config_id / "report.json"
    if not path.is_file():
        return None
    return json.loads(path.read_text())


def cell_row(
    architecture_id: str,
    sequence_id: str,
    report: dict[str, Any],
    which_stream: str,
) -> dict[str, Any]:
    stream = duration_row(report["duration_metrics"][which_stream])
    ep = report["episode_metrics"][which_stream]
    status = report.get("status_recovery_metrics", {}) if which_stream == "tim_target_memory" else {}
    return {
        "architecture_id": architecture_id,
        "sequence_id": sequence_id,
        "status": "available",
        "correct_s": stream["correct_target_duration_s"],
        "wrong_s": stream["wrong_target_duration_s"],
        "lost_s": stream["lost_target_duration_s"],
        "absent_valid_s": stream["target_absent_but_output_valid_duration_s"],
        "no_selection_s": stream["no_target_selected_duration_s"],
        "wrong_burst_count": ep["wrong_target_burst_count"],
        "wrong_handover_count": ep["wrong_handover_count"],
        "longest_wrong_burst_s": ep["longest_wrong_target_burst_s"],
        "recovery_attempt_count": status.get("recovery_attempt_count"),
        "correct_candidate_suppressed_duration_s": status.get(
            "correct_candidate_suppressed_duration_s"
        ),
        "note": None,
    }


def pending_row(architecture_id: str, sequence_id: str, status: str = "pending_annotation") -> dict[str, Any]:
    return {
        "architecture_id": architecture_id,
        "sequence_id": sequence_id,
        "status": status,
        "correct_s": None,
        "wrong_s": None,
        "lost_s": None,
        "absent_valid_s": None,
        "no_selection_s": None,
        "wrong_burst_count": None,
        "wrong_handover_count": None,
        "longest_wrong_burst_s": None,
        "recovery_attempt_count": None,
        "correct_candidate_suppressed_duration_s": None,
        "note": None,
    }


class NoPromotableConfiguration(ValueError):
    """No calibration candidate passes the asymmetric safety gate.

    This is a genuine scientific finding (the tracker may not expose
    enough viable candidates for TIM-MARS to validate safely), not a
    tooling error. Callers must record it explicitly, never substitute a
    silently-selected losing candidate.
    """

    def __init__(self, message: str, closest: dict[str, Any]):
        super().__init__(message)
        self.closest = closest


def select_calibrated_sort_config(
    calibration_agg_path: Path,
    gate: dict[str, Any],
) -> tuple[str, dict[str, Any]]:
    """Apply the manifest's asymmetric safety gate to the SORT calibration
    sweep and return the selected (config_id, cell_row) for dev_may_hard_reentry.

    A candidate is promotable only if it does not increase wrong-target or
    target-absence-but-output-valid duration beyond tolerance relative to
    raw SORT on the same sequence. Among promotable candidates, the one
    with the lowest wrong-target duration is selected; ties broken by
    lowest lost-target duration (never by a single blended scalar).

    Raises NoPromotableConfiguration (fail closed) if none qualify, with
    the closest-but-failing candidate attached for transparent reporting.
    """
    rows = json.loads(calibration_agg_path.read_text())
    baseline = next(r for r in rows if r["config_id"] == "baseline")
    raw_wrong = baseline["raw_wrong_s"]
    raw_absent = baseline.get("raw_absent_valid_s", 0.0)

    promotable = []
    for row in rows:
        if row["tim_wrong_s"] > raw_wrong + gate["wrong_target_tolerance_s"]:
            continue
        if row.get("tim_absent_valid_s", 0.0) > raw_absent + gate["absence_output_tolerance_s"]:
            continue
        promotable.append(row)

    if not promotable:
        closest = min(rows, key=lambda r: r["tim_wrong_s"])
        raise NoPromotableConfiguration(
            "no SORT+TIM calibration configuration passes the asymmetric "
            "safety gate on dev_may_hard_reentry "
            f"(raw_wrong_s={raw_wrong}, closest candidate "
            f"{closest['config_id']} still has tim_wrong_s={closest['tim_wrong_s']})",
            closest=closest,
        )

    promotable.sort(key=lambda r: (r["tim_wrong_s"], r["tim_lost_s"]))
    winner = promotable[0]
    return winner["config_id"], winner


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        raise ValueError(f"no rows to write for {path}")
    with path.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n")


def build(
    manifest: dict[str, Any],
    calibrated_sort_config_id: str | None,
    sort_tim_gate_failure: dict[str, Any] | None = None,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    availability = manifest["annotation_availability"]
    architectures = {a["id"]: a for a in manifest["architectures"]}
    sequences = [s["id"] for s in manifest["development_sequences"]]

    for sequence_id in sequences:
        seq_avail = availability[sequence_id]
        for architecture_id, architecture in architectures.items():
            tracker = architecture["tracker_type"]
            avail = seq_avail[tracker]

            if avail == "pending_annotation":
                rows.append(pending_row(architecture_id, sequence_id))
                continue

            if architecture["data_source"] == "reuse_p031":
                report = load_p031_cell(sequence_id)
                stream = (
                    "raw_target" if not architecture["tim_enabled"] else "tim_target_memory"
                )
                rows.append(cell_row(architecture_id, sequence_id, report, stream))
                continue

            # run_fresh
            if tracker == "sort":
                if sequence_id != "dev_may_hard_reentry":
                    rows.append(pending_row(architecture_id, sequence_id))
                    continue
                if architecture_id == "sort_tim" and calibrated_sort_config_id is None:
                    row = pending_row(
                        architecture_id, sequence_id, status="no_safe_configuration_found"
                    )
                    if sort_tim_gate_failure is not None:
                        row["wrong_s"] = sort_tim_gate_failure["tim_wrong_s"]
                        row["lost_s"] = sort_tim_gate_failure["tim_lost_s"]
                        row["note"] = (
                            f"closest candidate {sort_tim_gate_failure['config_id']}; "
                            "does not pass the asymmetric safety gate, not promoted"
                        )
                    rows.append(row)
                    continue
                config_id = (
                    calibrated_sort_config_id if architecture_id == "sort_tim" else "baseline"
                )
                report = load_p058_cell_from_calibration(sequence_id, config_id)
                stream = "raw_target" if not architecture["tim_enabled"] else "tim_target_memory"
                rows.append(cell_row(architecture_id, sequence_id, report, stream))
                continue

            if tracker == "deepsort":
                report = load_p058_cell(sequence_id, "deepsort_tim")
                if report is None:
                    rows.append(pending_row(architecture_id, sequence_id))
                    continue
                stream = "raw_target" if not architecture["tim_enabled"] else "tim_target_memory"
                rows.append(cell_row(architecture_id, sequence_id, report, stream))
                continue

            rows.append(pending_row(architecture_id, sequence_id))

    return rows


CALIBRATION_REPORT_DIR = (
    REPO_ROOT / "reports" / "p058_sort_tim_calibration_6231fdc1_2026_08_08" / "sequences"
)


def load_p058_cell_from_calibration(sequence_id: str, config_id: str) -> dict[str, Any]:
    path = CALIBRATION_REPORT_DIR / sequence_id / config_id / "report.json"
    return json.loads(path.read_text())


def main() -> int:
    manifest = load_manifest()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    calibration_agg_path = (
        REPO_ROOT
        / "reports"
        / "p058_sort_tim_calibration_6231fdc1_2026_08_08"
        / "aggregate"
        / "calibration_aggregate.json"
    )
    calibrated_id = None
    gate_failure = None
    if calibration_agg_path.is_file():
        cal_manifest = yaml.safe_load(
            (
                REPO_ROOT
                / "docs"
                / "data"
                / "lightweight_vs_integrated_tracking"
                / "p058_sort_tim_calibration_v1.yaml"
            ).read_text()
        )
        try:
            calibrated_id, winner = select_calibrated_sort_config(
                calibration_agg_path, cal_manifest["asymmetric_safety_gate"]
            )
            print(f"[ok] selected SORT+TIM calibration winner: {calibrated_id}")
            write_json(
                OUT_DIR / "sort_calibration_selection.json",
                {"config_id": calibrated_id, **winner},
            )
        except NoPromotableConfiguration as exc:
            gate_failure = exc.closest
            print(f"[finding] {exc}")
            write_json(
                OUT_DIR / "sort_calibration_selection.json",
                {
                    "config_id": None,
                    "status": "no_safe_configuration_found",
                    "message": str(exc),
                    "closest_candidate": exc.closest,
                },
            )

    rows = build(manifest, calibrated_id, sort_tim_gate_failure=gate_failure)
    write_csv(OUT_DIR / "matrix_all_cells.csv", rows)
    write_json(OUT_DIR / "matrix_all_cells.json", rows)

    available = sum(1 for r in rows if r["status"] == "available")
    pending = sum(1 for r in rows if r["status"] == "pending_annotation")
    no_safe = sum(1 for r in rows if r["status"] == "no_safe_configuration_found")
    print(
        f"[ok] {len(rows)} total cells: {available} available, {pending} "
        f"pending_annotation, {no_safe} no_safe_configuration_found"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
